
DECLARE
    LV_NUMERO NUMBER := 5235;
    LV_SUMA   NUMBER := 0;
BEGIN
    WHILE LV_NUMERO > 0 LOOP
        LV_SUMA := LV_SUMA + MOD(LV_NUMERO, 10);
        LV_NUMERO := TRUNC(LV_NUMERO / 10);
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('LA SUMA DE LOS DIGITOS ES: ' || LV_SUMA);
END;

//

DECLARE
    LV_CONTADOR NUMBER := 20;
BEGIN
    WHILE LV_CONTADOR >= 0 LOOP
        IF MOD(LV_CONTADOR, 2) = 0 THEN
            DBMS_OUTPUT.PUT_LINE(LV_CONTADOR);
        END IF;
        LV_CONTADOR := LV_CONTADOR - 1;
    END LOOP;
END;

//

DECLARE
    LV_BASE     NUMBER := 3;
    LV_EXPONENTE NUMBER := 4;
    LV_RESULTADO NUMBER := 1;
BEGIN
    FOR i IN 1..LV_EXPONENTE LOOP
        LV_RESULTADO := LV_RESULTADO * LV_BASE;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('RESULTADO DE LA POTENCIA: ' || LV_RESULTADO);
END;

//

DECLARE
    LV_NOMBRE VARCHAR2(20) := 'MARIO';
BEGIN
    FOR i IN 1..LENGTH(LV_NOMBRE) LOOP
        DBMS_OUTPUT.PUT_LINE('VALOR DE LA VARIABLE = ' || SUBSTR(LV_NOMBRE, i, 1));
    END LOOP;
END;

//

DECLARE
    LV_NUMERO NUMBER := 7;
    LV_ES_PRIMO BOOLEAN := TRUE;
BEGIN
    IF LV_NUMERO <= 1 THEN
        LV_ES_PRIMO := FALSE;
    ELSE
        FOR i IN 2..LV_NUMERO-1 LOOP
            IF MOD(LV_NUMERO, i) = 0 THEN
                LV_ES_PRIMO := FALSE;
                EXIT;
            END IF;
        END LOOP;
    END IF;

    IF LV_ES_PRIMO THEN
        DBMS_OUTPUT.PUT_LINE('EL NUMERO ES PRIMO');
    ELSE
        DBMS_OUTPUT.PUT_LINE('EL NUMERO NO ES PRIMO');
    END IF;
END;

//

DECLARE
BEGIN
    FOR i IN 1..10 LOOP
        DBMS_OUTPUT.PUT_LINE('TABLA DEL ' || i);
        FOR j IN 1..10 LOOP
            DBMS_OUTPUT.PUT_LINE(i || ' * ' || j || ' = ' || (i * j));
        END LOOP;
    END LOOP;
END;



