/*TRIGGERS(DISPARADORES): ES UN BLOQUE DE CODIGO QUE SE ECJUTA AUTOMATICAMENTE EN RESPUESTA DE CIERTOS EVENTOS EN UNA 
TABLA O EN UNA VISTA COMO:
    -INSERT
    -DELETE
    -UPDATE
PARA QUE QUE SE USAN LOS TRIGGERS?
SIRVEN PARA :
    -REGISTRAR AUDITORIAS(BITACORAS DE CAMBIO)
    -VALIDAR REGLAS DE NEGOCIO COMPLEJAS
    -MANTENER LA INTEGRIDAD DE LOS DATOS 
    -GENERAR VALORES AUTOMATICOS(POR EJEMPLEO TIMESTAP O USUARIO QUE MODIFICO)
TIPOS DE TRIGGER
    -BEFORE -> SE EJECUTA ANTES DE QUE OCURRA LA OPERACION
    -AFTER -> SE EJECUTA DESPUES QUE OCURRA LA OPERACION
    -INSTEAD OF -> SE USA EN VUISTAS, REMPLAZANDO UNA OPERACION DML 
NIVEL DE TRIGGER
    -ROW(POR FILA) : EL TRIGGER SE ACTIVA UNA VEZ POR CADA FILA AFECTADA
    -STATEMENT(POR SENTENCIA) : EL TRIGGER SE ACTIVA UNA SOLA VEX POR UNA INSTRUCCION SQL SIN IMPORTAR CUANTAS FILAS
    SE VEAN AFECTADAS
    
    --VERIABLES ESPECIALES(IDENTIFICADORES DE CORRELACION) QUE SE USA UNICAMENTE EN TRIGGER FOR EACH ROW(POR FILA)
        :OLD -> REPRESENTA LOS VALORES ANTERIORES(ANTES DE MODIFICAR)
        :NEW -> REPORESENTA LOS VALORES NUEVOS(DESPUES DE INSERTAR O MODIFICAR 
    SOLOS FUNCIONAN EN TRIGGER FOR EACH ROW
    
*/


--REALIZAR UN TRIGGER DE TIPO AFTER FOR EACH ROW PARA REALIZAR LA AUDITORIA DE LOS EVENTOS QUE OCURRAN SOBRE UNA TABLA

CREATE TABLE COMPUTADORA(
    ID_COMPU NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    RAM NUMBER,
    PROCESADOR NVARCHAR2(100),
    PRECIO NUMBER,
    CONSTRAINT COMPU_PK PRIMARY KEY(ID_COMPU)
);

---GENERAR UNA TABLA PARA REGISTRAS LO MIVIEMTOS OCURRIDO EN LA TABLA COMPUTADORA

CREATE TABLE BIT_COMPUTADORA(
    ID_BIT NUMBER, 
    --CAMSPOS DE COMPUATADORA
    --REPRESENTAN LOS VALORES NUEVOS(CUANDO OCUURA UN INSERT O UN UPDATE)
    ID_COMPU NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    RAM NUMBER,
    PROCESADOR NVARCHAR2(100),
    PRECIO NUMBER, 
    --REPRESENTAR LOS VALORES VIEJOS(CUANDO OCURRE UN DELETE O UPDATE)
    MARCA_OLD NVARCHAR2(100),
    MODELO_OLD NVARCHAR2(100),
    RAM_OLD NUMBER,
    PROCESADOR_OLD NVARCHAR2(100),
    PRECIO_OLD NUMBER, 
    --CAMPOS PARA EL CONTROL(USUARIO, FECHA Y EL TIPO DE MOVIMIENTO QUE MODIFICO LA TABLA COMPUTADORA)
    USUARIO NVARCHAR2(100),
    FECHA_MOV DATE,
    MOVIMIENTO NVARCHAR2(100),
    CONSTRAINT BIT_COMPU_PK PRIMARY KEY(ID_BIT)
);

--TRIGGER AFTER A NIVEL FILA SIMPLE
CREATE OR REPLACE TRIGGER TR_I_COMPUTADORA
AFTER INSERT ON COMPUTADORA
FOR EACH ROW --TRIGGER A NIVEL FILA
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
BEGIN
    --RECUPERAR USUARIO DEL SYSTEMA 
    SELECT USER INTO LV_USUARIO FROM DUAL;
    --RECUPERAR LA FECHA 
    SELECT SYSDATE INTO LV_FECHA FROM DUAL;
    --RECUPERAR UN ID VALIDO EN AUTOINCREMETO 
    SELECT NVL(MAX(ID_BIT),0) + 1 INTO LV_ID_BIT FROM BIT_COMPUTADORA;
    --HACEMOS ESTO, PORQUE SON VALORES QUE EL TRIGGER NO VA A PODER MANEJAR EN AUTOMATICO Y NECESITAMOS INDICARLE
    --CUALES SON LOS VALORES QUE DEBE ESCRIBIR EN LOS CAMPOS DE CONTROL 
    
    INSERT INTO BIT_COMPUTADORA(ID_BIT, ID_COMPU, MARCA,MODELO,RAM,PROCESADOR,PRECIO,MARCA_OLD,MODELO_OLD,RAM_OLD,
        PROCESADOR_OLD,PRECIO_OLD,USUARIO,FECHA_MOV,MOVIMIENTO)
    VALUES(LV_ID_BIT,:NEW.ID_COMPU,:NEW.MARCA,:NEW.MODELO,:NEW.RAM,:NEW.PROCESADOR,:NEW.PRECIO, NULL, NULL,0,NULL,
    0,LV_USUARIO,LV_FECHA,'INSERT');
END TR_I_COMPUTADORA;
/

SELECT * FROM COMPUTADORA;
SELECT * FROM BIT_COMPUTADORA;

INSERT INTO COMPUTADORA VALUES(1, 'HP', 'PAVILON', 16, 'INTEL CORE i9 12th', 15000);
    
--ACTIVIDAD: REALIZAR EL TRIGGER SIMPLE PARA DELETE Y EL TRIGGER SIMPLE PARA UPDATE DE LA TABLA COMPUTADORA
--HACER LAS PRUEBAS CON POR MEOS 3 REGSITROS



