----VISTAS COMPLEJAS 

SELECT * FROM PADRE;
SELECT * FROM HIJO;

--MOSTRAR CON UNA EL NOMBRE DEL HIJO Y SU PADRE 
CREATE OR REPLACE VIEW V_HIJO_PADRE AS
SELECT H.NOMBRE, P.NOMBRE AS PADRE
FROM HIJO H 
INNER JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;

SELECT * FROM  V_HIJO_PADRE;

--VISTAS USANDO FUNCIONES DE AGREGACION

--SUMA LOS EDADES DEL PADRE POR PROFESION
CREATE OR REPLACE VIEW V_SUMA_EDADES AS
SELECT TRABAJO, SUM(EDAD) AS SUMA_EDADES
FROM PADRE
GROUP BY TRABAJO;

SELECT * FROM V_SUMA_EDADES;
