--OPEREACIONES QUE SE MANEJAN EN SQL 
--DDL->LENGUAJE PARA DEFINIR Y MODIFICAR LA ESTRUCTURA DE LOS OBEJTOS EN LA BASE DATOS -> CREATE, UPDATE, ALTER Y DROP
--DML->LENGUAJE DE MANIPULACION DE DATOS->SELECT, INSERT, UPDATE, DELETE
--DCL->LENGUAJE DE CONTROL DE DATOS->GRANT Y REVOKE

--CREACION DE UN NUEVO USUARIO 

--MODIFICAR LA SESION ACUTAL PARA LA EJECUCION DE SCRIPTS: CUANDO SE EJECUTARA UNA SENTENCIA
--QUE SIGNIFICA TENER LOS PERMISOS NECESARIOS DE ORACLE PARA QUE SE REALICE, SE MODIFCA LA SESION Y ENTOCES PODEMOS
--EJECUTAR CUALAQUIER TIPO OPERACION EN LA QUE SE PUEDA VER AFECTADA MI BASE DE DATOS(LE DAMOS TODOS LO PERMISOS)
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; --EJECUTAR CON CRTL + ENTER ANTES DEL PUNTO Y COMA 
--CREACION DE UN USUARIO CON CONTRASENIA
CREATE USER CURSOBD IDENTIFIED BY 12345;
--OTOGAR TODOS LOS PRIVILEGIOS AL NUEVO USUARIOS
GRANT ALL PRIVILEGES TO CURSOBD;
