/*CURSOR ES UN MECANISMO QUE USA PL/SQL PARA RECORRER REGISTROS DE UNA CONSULTA
SQL DE FORMA FILA POR FILA

CUANDO EJECUTAS UN SELECT EN PL/SQL QUE DEVUELVE UNA SOLA FILA PUEDE USAR EL SELECT..INTO
PERO SI EL SELECT DEVULVE VARIAS FILAS, NECESITAS UN CURSOR PARA RECORRELAS UNA A UNA

CURSORES IMPLICITOS 
    SE CREAN AUTOMATICMANETE CUANDO EJECUTAS UN INSERT, UPDATE, DLETE O SELECT INTO
    NO ES NECESARIO DECLAREARLO 
    
CURSORES EXPLICITOS 
    LOS DECLARAS TU MISMO
    SE USAN PARA RECORRES RESULTADOS DE UJN SELECT QEU DEVULEVE VARIAS FILAS 
    TIENE 4 PASOS A SEGUIR 
    DECLARAR -> ABRIR -> RECUPERAR -> CERRAR*/
 SELECT * FROM LIBRO;   
CREATE OR REPLACE PROCEDURE PR_DETALLE_LIBRO
IS
    --1.- DECLARAR EL CURSOR
    CURSOR LIBRO_INFO IS 
        SELECT NOMBRE, (
            CASE GENERO
            --1.DRAMA,2.TERROR,3.CIENCIA FICCION,4.NOVELA,5.TRILLER
                WHEN 1 THEN 'DRAMA'
                WHEN 2 THEN 'TERROR'
                WHEN 3 THEN 'CIENCIA FICCION'
                WHEN 4 THEN 'NOVELA'
                WHEN 5 THEN 'TRILLER'
                ELSE 'SIN GENERO'
                END) AS GENERO, PRECIO FROM LIBRO;
        --VARIABLES
        LV_NOMBRE LIBRO.NOMBRE%TYPE; --ESTA FUNCION NOS INDICA QUE LA VARIABLE DECLARA SOLO PUEDE ALMACENAR EL NOMBRE
        LV_GENERO NVARCHAR2(100);
        LV_PRECIO NUMBER;
BEGIN
    --2.-ABRIR EL CURSOR
    OPEN LIBRO_INFO;
    
    --3.-RECUPERAR EL CURSOR
    LOOP
        --RECORRER CADA FILA 
        FETCH LIBRO_INFO INTO LV_NOMBRE, LV_GENERO, LV_PRECIO;
        --CONDICION SALIR CUANDO YA NO ENCUNTRE INFORMACION 
        EXIT WHEN LIBRO_INFO%NOTFOUND;
        --MOSTRAR LOS DATOS DLE CURSOR
        DBMS_OUTPUT.PUT_LINE('NOMBRE DEL LIBRO: '||LV_NOMBRE||', ES DE GENERO '||LV_GENERO||' Y TIENE UN PRECIO DE '||
        LV_PRECIO);
    END LOOP;
    --4.-CERRAR EL CURSOR
    CLOSE LIBRO_INFO;
END PR_DETALLE_LIBRO;
/

BEGIN 
    PR_DETALLE_LIBRO;
END;
/