/*SECUENCIA O SEQUENCE :
ES UN BLOQUE O OBEJTO PL/SQL QUE GENERA NUMERO CONSECUTIVOS, SIN IMPORTAR CUENTAS VECES LO USES
O DESDE QUE TABLEA

SE USA PRINCIPALMENTE PARA CREAR VALORES UNICOS DE IDENTIFICADORES(ID) POR EJEMPLO LA CLAVE PRIMARIA DE UNA TABLAS
*/

CREATE SEQUENCE S_ID_BIT
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999
NOCACHE
NOCYCLE;

--LLAMA LA SECUENCIA 
SELECT S_ID_BIT.NEXTVAL FROM DUAL;