/*PROCEDIMIENTO ALMACENADO(STORED PROCEDURE): ES UN BLOQUE DE CODIGO SQL QUE SE GUARDA
Y EJECUTA DIRECTAMENTE EN EL SERVIDOR DE LA BASE DE DATOS, ES UNA UNIDAD REUTILIZABLE
DE PROGRMACION QUE PUEDE REALIZAR TAREAS COMO CONSULTAS, INSERCIONES, ACTUALIZACIONES, 
VALIDACIONES Y MAS

PARA QUE SIRVE?
SIRVE PARA AUTOMATIZAR TAREAS REPETITIVAS EN LA BASE DE DATOS, COMO

    -VALIDAR DATOS ANTES DE INSERTALOS,
    -ACTUALIZAR VARIAS TABLAS AL MISMO TIEMPO
    -GENERAR REPORTES
    -SIMPLIFICAR LA LOGICA EN LAS APLICACIONES 
    -MEJORAR EL RENDIEMIENTO Y SEGUIRDAD(PORQUE LA LOGICA SE QUEDA EN EL SERVIDOR)
    
VENTAJAS DE USAR PROCEDIMIENTO ALMACENADO 
    -REDUCE EL TRAFICO ENTRE LA APLICACUION Y LA BASE DE DTAOS
    -PUEDE REUTILIZAR EL CODIGO MUCHAS VECES
    -MEJORAS EL CONTROL Y LA VALIDACION DE DATOS
    -CENTRALIZAS LA LOGICA DE NEGOCIO
    
*/

INSERT INTO COMPUTADORA VALUES (1, 'HP', 'Pavilion 15', 8, 'Intel Core i5', 14500);
INSERT INTO COMPUTADORA VALUES (2, 'Dell', 'Inspiron 14', 16, 'Intel Core i7', 18900);
INSERT INTO COMPUTADORA VALUES (3, 'Lenovo', 'ThinkPad E14', 8, 'AMD Ryzen 5', 16500);
INSERT INTO COMPUTADORA VALUES (4, 'Asus', 'VivoBook 15', 12, 'Intel Core i5', 15800);
INSERT INTO COMPUTADORA VALUES (5, 'Acer', 'Aspire 5', 16, 'AMD Ryzen 7', 19500);
INSERT INTO COMPUTADORA VALUES (6, 'HP', 'Envy 13', 16, 'Intel Core i7', 22000);
INSERT INTO COMPUTADORA VALUES (7, 'Dell', 'XPS 13', 16, 'Intel Core i7', 28000);
INSERT INTO COMPUTADORA VALUES (8, 'Lenovo', 'IdeaPad 3', 8, 'AMD Ryzen 3', 12000);
INSERT INTO COMPUTADORA VALUES (9, 'Asus', 'ROG Strix', 32, 'Intel Core i9', 45000);
INSERT INTO COMPUTADORA VALUES (10, 'Acer', 'Nitro 5', 16, 'AMD Ryzen 7', 25000);

INSERT INTO COMPUTADORA VALUES (11, 'HP', 'ProBook 450', 8, 'Intel Core i5', 17500);
INSERT INTO COMPUTADORA VALUES (12, 'Dell', 'Latitude 5420', 16, 'Intel Core i7', 23500);
INSERT INTO COMPUTADORA VALUES (13, 'Lenovo', 'Yoga Slim 7', 16, 'AMD Ryzen 7', 26000);
INSERT INTO COMPUTADORA VALUES (14, 'Asus', 'ZenBook 14', 16, 'Intel Core i7', 27000);
INSERT INTO COMPUTADORA VALUES (15, 'Acer', 'Swift 3', 8, 'Intel Core i5', 16000);
INSERT INTO COMPUTADORA VALUES (16, 'HP', 'Victus 16', 32, 'AMD Ryzen 9', 38000);
INSERT INTO COMPUTADORA VALUES (17, 'Dell', 'G15 Gaming', 16, 'Intel Core i7', 29000);
INSERT INTO COMPUTADORA VALUES (18, 'Lenovo', 'Legion 5', 32, 'AMD Ryzen 7', 35000);
INSERT INTO COMPUTADORA VALUES (19, 'Asus', 'TUF F15', 16, 'Intel Core i7', 26500);
INSERT INTO COMPUTADORA VALUES (20, 'Acer', 'Predator Helios', 32, 'Intel Core i9', 48000);


SELECT * FROM COMPUTADORA;

--RELIZAR UN RESPLADO DE LA TABLA COMPUTADORA EN OTRA TABLA 

--CREAR LA TABLA PARA CREAR EL RESPALDO 
CREATE TABLE COMPUTADORA_PRD(
    ID_COMPU NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    RAM NUMBER,
    PROCESADOR NVARCHAR2(100),
    PRECIO NUMBER,
    CONSTRAINT COMPU_PRD_PK PRIMARY KEY(ID_COMPU)
);

CREATE OR REPLACE PROCEDURE PR_RESPALDO_COMPUTADORA
IS
--DECLRACION DE VARIABLES, CONSTANTE O CURSORES
BEGIN
    --PARA PODER REURILIR ESTE PROCEDIMIENTO, PRIMERO LIMPIAMOS LA TABLA COMPUTADORA_PRD
    DELETE FROM COMPUTADORA_PRD;
    
    --REALIAZAR EL RESPALDO DE COMPUTADORA EN COMPUTADOR_PRD
    INSERT INTO COMPUTADORA_PRD(ID_COMPU, MARCA,MODELO, RAM, PROCESADOR, PRECIO)
    SELECT ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO FROM COMPUTADORA;
END PR_RESPALDO_COMPUTADORA;
/

SELECT * FROM COMPUTADORA;
SELECT * FROM COMPUTADORA_PRD;

--EKECUTAR EL PROCEDIMIENTO 
EXECUTE PR_RESPALDO_COMPUTADORA;

--aplicar un descuento a todos los registros de la tabla computadora 
CREATE OR REPLACE PROCEDURE APLICAR_DESCUENTO(P_DESCUENTO IN NUMBER) --ESTE PARAMETRO ME VA A INDICAR EL % DE DESC
IS
BEGIN
    UPDATE COMPUTADORA
    SET PRECIO = PRECIO - (PRECIO * (P_DESCUENTO / 100));
    
    --IMIPIRMIR UN MENSAJE PARA INDICAR QUE SI SE APL9ICO EL CAMBIO
    DBMS_OUTPUT.PUT_LINE('SE APLICO UN DESCUENTO DEL ' ||P_DESCUENTO||'% A TODOS LAS COMPUTADORA');
END APLICAR_DESCUENTO;
/
SELECT * FROM COMPUTADORA;
EXECUTE APLICAR_DESCUENTO(10);
ROLLBACK;

