--TRIGGER A NIVEL SENTENCIA (STATEMENT): SE EKECUTA UN VEZ POR SENTECIA DML 

--BITACORA QUE SOLO ME REGISTRE EL MOVIENTO, USUARIO Y FECHA

CREATE TABLE BIT_COMPU_MOV(
    ID_BIT_MOV NUMBER,
    USUARIO NVARCHAR2(100),
    FECHA_MOV DATE,
    MOVIMIENTO NVARCHAR2(100),
    CONSTRAINT BIT_COMPU_MOV_PK PRIMARY KEY(ID_BIT_MOV)
);

--TRIGGER A NIVEL SENTENCIA 
CREATE OR REPLACE TRIGGER TR_S_MULTIPLE_COMPU
AFTER INSERT OR UPDATE OR DELETE ON COMPUTADORA
---CUANDO ES UN TRIGGER A NIVEL SNETENCIA NO SE ESCRIBE EL FOR EACH ROW
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
    LV_MOV NVARCHAR2(10);
BEGIN
    --RECUPERAR DATO DEL SYSTEMA Y UN ID VALIDO
    SELECT S_ID_BIT.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FECHA FROM DUAL;
    
    IF INSERTING THEN
        LV_MOV := 'INSERT';
    ELSIF UPDATING THEN
        LV_MOV := 'UPDATE';
    ELSIF DELETING THEN
        LV_MOV := 'DELETE';
    END IF;
        INSERT INTO BIT_COMPU_MOV(ID_BIT_MOV, USUARIO, FECHA_MOV, MOVIMIENTO)
            VALUES(LV_ID_BIT, LV_USUARIO, LV_FECHA, LV_MOV);
END TR_S_MULTIPLE_COMPU;
/

--------------------------------------
SELECT * FROM COMPUTADORA;
SELECT * FROM BIT_COMPU_MOV;
SELECT * FROM BIT_COMPUTADORA;


INSERT INTO COMPUTADORA VALUES(2, 'HP', 'PAVILON', 16, 'INTEL CORE i9 12th', 15000);
INSERT INTO COMPUTADORA VALUES(3, 'DELL', 'INSPIRON', 8, 'INTEL CORE i9 12th', 7000);
DELETE FROM COMPUTADORA;

