--DDL PARA CREAR LA TABLA EMPLEADO 

CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100)
);

--CREAR VALORES NUEVOS EN MI TABLE, OPERACIONES DML

INSERT INTO EMPLEADO VALUES(1, 'DANIEL', 'GOMEZ',26,'GERENTE DE ADMINISTRACIO', 'ADMINITRACION');
COMMIT; --CONFIRMAMOS LOS CAMBIOS QUE ACABAMOS DE HACER , SIEMPRE QUE SEA UNA OPRECION INSERT,
--UPDATE, DELETE SE DEBE CONFIRMAR EL CAMBIO INMEDIATAMENTE USANDO COMMIT (F11)

SELECT * FROM EMPLEADO;

--METODO PARA ELIMINAR

--EJECUTAR UN DDL PARA ELIMINAR LOS REGISTROS 
DELETE FROM EMPLEADO; --ELIMINAR LOS REGISTROS DENTRO DE LA TABLA

--EJECUTAR UN DML PARA ELIMINAR LA TABLA 
DROP TABLE EMPLEADO; --ELIMINA LA TABLA DE LA BASE DE DATOS 

--USO DE LOS CONSTRAINT

--EJEMPLO 1 DE USO DE PRIMARY KEY 
CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100)
);

--SEGUNDA FORMA 
CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100),
    PRIMARY KEY(ID_EMPLEADO)
);

--TERCERA FORMA 
CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100),
    CONSTRAINT EMPLEADO_PK PRIMARY KEY(ID_EMPLEADO)
);





